defaults:
  # these are available for substitution in templates
  variables:
    # Version of the practical guide (added to all releases)
    version: "v2021-02-10"
    # Language and text direction for Jekyll site and epub
    html-language: "en"
    html-dir: "ltr"

  # File name used for build targets
  target_filename: "mdtools-docs"

  source: content/src
  structure: config/structure.yaml
  # That must be .po for translations, and .pot for the source language!
  localization: content/localization.pot

  # glossary: yaml file with glossary terms
  glossary: content/glossary.yaml
  # glossary-items: number of glossary items per page (used for deckset and revealjs)
  glossary-items: 20
  # glossary-style: plain:glossary style for ebook builder (plain(default)|footnotes|underline)
  glossary-style: plain

  # target::Target file (for reveal.js and deckset) or folder (for wordpress or jekyll).
  target: ""
  # template: The template to use (deckset, revealjs, and jekyll output)
  template: ""
  # the target format (html, markdown, latex)
  target-format: ""
  # autogenerated prefix for each pattern headline(e.g. "Pattern 1.5: Describe Organizational Drivers")
  pattern_prefix: "%(chapter)s.%(section)s:"

presets:
  jekyll:
    renderer: jekyll
    target-format: html
    noob_menu: true
    # add "read next" below content pages
    read-next-navigation: true
    read-next-shortcuts: true 
    variables:
      # CNAME for GitHub-Page
      # microsite_cname: "mdtools.evolvingcollaboration.com"

      # URL o the Github project
      github-url: "https://github.com/bboc/mdtools"
      # URL of the website
      site-url: "https://bboc.github.io"

    # build content files
    target: docs/

    templates:
      # main website index.html, 404 and map
      - source: content/website/_templates/index.html
        destination: docs/index.html
        mode: markdown
      - source: content/website/_templates/404.md
        destination: docs/404.md
        mode: copy
      - source: templates/website/pattern-map.html
        destination: docs/_includes/pattern-map.html
      - source: templates/website/map.md
        destination: docs/map.md
        mode: copy
      # layouts for website
      - source: templates/website/_layouts/default.html
        destination: docs/_layouts/default.html
      - source: templates/website/_layouts/plain.html
        destination: docs/_layouts/plain.html
      # includes for website (header contains {{menu}})
      - source: content/website/_includes/footer.html
        destination: docs/_includes/footer.html
      - source: content/website/_includes/header.html
        destination: docs/_includes/header.html
        mode: html
      # other website config files
      - source: templates/website/_config.yml
        destination: docs/_config.yml
      # - source: templates/website/CNAME
      #   destination: docs/CNAME

  all-in-one-jekyll-page:
    # a single-page-version for the website
    renderer: ebook
    template: templates/website/all-in-one-page.md
    target: docs/all.md
    target-format: html
    header-offset: 1

  epub:
    renderer: ebook
    target: tmp/epub-compiled.md
    target-format: epub
    template: templates/epub-header.md
    templates:
        - source: templates/epub.css
          destination: tmp/epub.css

  ebook:
    renderer: ebook
    target-format: latex
    target: tmp/ebook-compiled.md
    # template is empty on purpose, because it is not required
    template: ""
    # copy md and LaTeX templates
    templates:
      - source: config/ebook.tex
        destination: tmp/ebook.tex
      - source: config/ebook-style.sty
        destination: tmp/ebook-style.sty

  revealjs:
    renderer: revealjs
    # reveal.js config option for RTL languages
    revealjs-rtl: "false"