config:
  title: title
  end: SKIP

parts:
  - id: introduction
    parts:
      - usecases
  - id: formats
    parts:
      - deckset
      - jekyll
  - id: features
    parts:
      - glossary-entries
      - section-links
      - id: chapter-headers
        tags: [obsolete]      
      - id: index-files
        tags: [obsolete]
  - id: data-structure
    parts:
      - structure-definition
      - configuration
      - templates
  - id: macros
    parts:
      - index-macro
      - index-demo-summary
      - index-demo-searchable
      - menu-macro
  - id: commands
    parts:
      - makefile-and-temp-folder
      - mdbuild
      - mdslides
      - mdimg
  - id: translation
    parts:
      - translating-templates
  - id: appendix
    parts:
    - glossary
    - changelog
    - site-index
    - license
