# Site settings
title: mdtools Documentation
email: bernhard.bockelbrink@gmail.com
description: > # this means to ignore newlines until "baseurl:"
   A set of commandline tools for creating slide decks, ebooks and websites.

baseurl: "/mdtools" # the subpath of your site, e.g. /blog
url: "https://bboc.github.io" # the base hostname & protocol for your site

# Build settings
source:   .
destination:  ./_site
layouts_dir:  ./_layouts
includes_dir: ./_includes


markdown: kramdown
safe: true # required on Github pages (no plugins)

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page" # overrides previous default layout


exclude:      [
  "_export",
  "_python",
  "_templates",
  ]
